name: Deploy to EC2 via S3

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"

      - name: Upload Build Files to S3
        run: |
          echo "🚀 S3 업로드 시작..."
          aws s3 cp --recursive .next s3://clienttbucket/.next/
          aws s3 cp package.json s3://clienttbucket/
          aws s3 cp --recursive public s3://clienttbucket/public/
          aws s3 cp --recursive node_modules s3://clienttbucket/node_modules/
          echo "✅ S3 업로드 완료!"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ EC2에 배포 스크립트 실행 중..."
            chmod +x /home/ubuntu/deploy.sh
            /home/ubuntu/deploy.sh
            echo "🚀 배포 완료!"

      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "Spidey Bot", "content": "🕷️ **배포 완료!** 🚀\n🔗 https://moim.team"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}